### ISSUE TITLE
Thinking of making a similar mod, is it alright if I use the kerbal swap code?

### ISSUE THREAD

**Issue by DeltaDizzy** [linuxgurugamer/KerbalHotSeat#2]
For a while I have been wanting a mod that lets you choose what seats kerbals go into. I realized the mod would be like this except you get to choose where and when the kerbals go. I don't want to reinvent the wheel, so i wondered if it was OK to use the code that swaps kerbals. I know KerbalHotSeat is CC BY-NC-SA, but I usually get permission anyways just to be on the safe side and to ask an questions if I have to.

**Comment by linuxgurugamer** [comment]
No problem.  Just provide a credit both to the original author and myself.
Thanks for asking
